apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-2-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: my-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/my-apps/my-app2
    repoURL: https://github.com/mmanirmd/argocd-app2.git
    targetRevision: HEAD
  syncPolicy:
     automated:
      selfHeal: true
      prune: true
