apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-2-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: my-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/my-apps/my-app1
    repoURL: https://github.com/mmanirmd/argocd-app2.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
